import express from 'express';
import fs from 'fs';
import path from 'path';
import PDFDocument from 'pdfkit';
import protect from '../middleware/auth.js';
import OcrResult from '../models/OcrResult.js';

const router = express.Router();

// Ensure exports directory exists
const exportsDir = './exports';
if (!fs.existsSync(exportsDir)) {
  fs.mkdirSync(exportsDir, { recursive: true });
}

// @desc    Generate export file (txt or pdf)
// @route   POST /api/export/:resultId
// @access  Private
router.post('/:resultId', protect, async (req, res) => {
  try {
    const ocrResult = await OcrResult.findById(req.params.resultId).populate('documentId');
    
    if (!ocrResult) {
      return res.status(404).json({ message: 'OCR Result not found' });
    }

    // Verify ownership
    if (ocrResult.documentId.userId.toString() !== req.user.id) {
      return res.status(403).json({ message: 'Not authorized to export this document' });
    }

    const { format } = req.body;
    const exportFormat = (format || 'txt').toLowerCase();

    if (!['txt', 'pdf'].includes(exportFormat)) {
      return res.status(400).json({ message: 'Supported export formats: txt, pdf' });
    }

    const timestamp = Date.now();

    if (exportFormat === 'txt') {
      // Plain text export
      const filename = `export-${ocrResult._id}-${timestamp}.txt`;
      const exportPath = path.join(exportsDir, filename);
      fs.writeFileSync(exportPath, ocrResult.extractedText);

      return res.json({
        message: 'Export file generated successfully',
        filename,
        downloadUrl: `/api/export/download/${filename}`
      });
    }

    if (exportFormat === 'pdf') {
      // PDF export using PDFKit
      const filename = `export-${ocrResult._id}-${timestamp}.pdf`;
      const exportPath = path.join(exportsDir, filename);
      const writeStream = fs.createWriteStream(exportPath);

      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 60, bottom: 60, left: 50, right: 50 }
      });

      doc.pipe(writeStream);

      // --- Header ---
      doc
        .fontSize(22)
        .fillColor('#1e293b')
        .text('DataLens OCR — Transcription Report', { align: 'center' });
      
      doc.moveDown(0.3);

      // Thin separator line
      doc
        .strokeColor('#94a3b8')
        .lineWidth(0.5)
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .stroke();

      doc.moveDown(0.8);

      // --- Metadata block ---
      const originalFilename = ocrResult.documentId?.originalFilename || 'Unknown';
      const confidence = ocrResult.confidence != null ? (ocrResult.confidence * 100).toFixed(1) + '%' : 'N/A';
      const modelUsed = ocrResult.modelUsed || 'TrOCR';
      const processingTime = ocrResult.processingMs != null ? ocrResult.processingMs + ' ms' : 'N/A';
      const exportDate = new Date().toLocaleString();

      doc.fontSize(10).fillColor('#64748b');
      doc.text(`Source File:  ${originalFilename}`);
      doc.text(`Confidence:   ${confidence}`);
      doc.text(`Model:        ${modelUsed}`);
      doc.text(`Processing:   ${processingTime}`);
      doc.text(`Exported:     ${exportDate}`);

      doc.moveDown(0.6);

      // Another separator
      doc
        .strokeColor('#cbd5e1')
        .lineWidth(0.3)
        .moveTo(50, doc.y)
        .lineTo(545, doc.y)
        .stroke();

      doc.moveDown(1);

      // --- Extracted Text ---
      doc
        .fontSize(12)
        .fillColor('#0f172a')
        .text(ocrResult.extractedText || '(No text extracted)', {
          align: 'left',
          lineGap: 4
        });

      // --- Footer ---
      doc.moveDown(2);
      doc
        .fontSize(8)
        .fillColor('#94a3b8')
        .text('Generated by DataLens — AI-Powered Handwriting Recognition Platform', {
          align: 'center'
        });

      doc.end();

      // Wait for the file to finish writing
      writeStream.on('finish', () => {
        res.json({
          message: 'PDF export generated successfully',
          filename,
          downloadUrl: `/api/export/download/${filename}`
        });
      });

      writeStream.on('error', (err) => {
        console.error('PDF Write Error:', err);
        res.status(500).json({ message: 'Failed to generate PDF file' });
      });
    }

  } catch (error) {
    console.error('Export Generation Error:', error);
    res.status(500).json({ message: error.message });
  }
});

// @desc    Download generated export file
// @route   GET /api/export/download/:filename
// @access  Private
router.get('/download/:filename', protect, async (req, res) => {
  try {
    const filename = req.params.filename;
    
    // Security check to avoid directory traversal
    if (filename.includes('..') || filename.includes('/') || filename.includes('\\')) {
      return res.status(400).json({ message: 'Invalid file path requested' });
    }

    const filePath = path.resolve(exportsDir, filename);

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ message: 'Export file not found' });
    }

    res.download(filePath, (err) => {
      if (err) {
        console.error('Download Transfer Error:', err);
        res.status(500).send('Could not download file');
      }
    });
  } catch (error) {
    res.status(500).json({ message: error.message });
  }
});

export default router;
